spring.application.name=weather-backend

#spring.h2.console.enabled=true
#spring.datasource.url=jdbc:h2:mem:weatherdb
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true

weather.api.key=${WEATHER_API_KEY}

#use db instead of localhost because we are creating multiple containers and each container cant access
#through localhost , so we use db , which is the postgres container name we put
spring.datasource.url=jdbc:postgresql://db:5432/weatherdb
#db connection

spring.jpa.open-in-view=false

#db user and pass
spring.datasource.username=postgres
spring.datasource.password=mayank0201

#hibernate auto updates schema
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
#prints sql queries
spring.jpa.properties.hibernate.format_sql=true

#redis config
spring.data.redis.host=redis
spring.data.redis.port=6379

# actuator endpoints exposure
management.endpoints.web.exposure.include=health,info,metrics,env,loggers

# always show health details
management.endpoint.health.show-details=always

# enable info endpoint details
management.info.env.enabled=true

# app metadata
info.app.name=Weather Backend
info.app.description=Production-ready weather service with caching and rate limiting
info.app.version=1.0.0