spring.application.name=weather-backend

#spring.h2.console.enabled=true
#spring.datasource.url=jdbc:h2:mem:weatherdb
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true

weather.api.key=${WEATHER_API_KEY}

#use db instead of localhost because we are creating multiple containers and each container cant access
#through localhost , so we use db , which is the postgres container name we put
spring.datasource.url=jdbc:postgresql://db:5432/${POSTGRES_DB}
#db connection

#db user and pass
spring.datasource.username=${POSTGRES_USER}
spring.datasource.password=${POSTGRES_PASSWORD}

#hibernate auto updates schema
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
#prints sql queries
spring.jpa.properties.hibernate.format_sql=true