spring.application.name=cinetracker-backend

spring.datasource.url=jdbc:postgresql://localhost:5432/cinetracker
spring.datasource.username=postgres
spring.datasource.password=mayank0201

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=8080

jwt.secret=aBl3l2Cb6hNwHLJnr4V/xDRZw6aBjPg4OwW6GCdV1gs=
jwt.expiration=3600000

