spring.application.name=cinetracker-backend

spring.config.import=optional:classpath:.env

spring.datasource.url=jdbc:postgresql://localhost:5432/cinetracker
spring.datasource.username=postgres
spring.datasource.password=${PQSL_DB_PASSWORD}
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=8080

jwt.secret=${JWT_SECRET}
jwt.expiration=3600000
jwt.refresh-expiration=604800000

tmdb.api.key=${TMDB_API_KEY}
tmdb.api.base-url=https://api.themoviedb.org/3

spring.data.redis.host=redis
spring.data.redis.port=6379

spring.cache.type=redis