spring.application.name=cinetracker-backend

spring.datasource.url=jdbc:postgres://localhost:5432/cinetracker
spring.datasource.username=postgres
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=8080

jwt.secret=${JWT_SECRET}
jwt.expiration=3600000

